## Introduction to Tensors

In [78]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [79]:
# Create tensrors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [80]:
#check the number of the dimensions of a tensor (ndim stands for number of dimension)
scalar.ndim

0

In [81]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [82]:
#check the dimension of our vector
vector.ndim

1

In [83]:
#create a matrix has more than 1 dimension
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [84]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [85]:
another_matrix.ndim

2

In [86]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [87]:
tensor.ndim

3

*Scalar: a single number
*Vector: a number with direction
*Matrix: a 2-dimensional array of numbers
*Tensor: an n-dimensional array of numbers

In [88]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [89]:
# change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor
# it can change by using assign attribute

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [90]:
# change unchangeable tensor
#unchangeable_tensor[0].assign(7)
# unchangeable tensor can not be changeable as above.

# Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [91]:
random_1= tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1= random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
print(random_2)
print(random_1)
# Are they equal?
random_1==random_2
# They are equal because we used same seed numbers.
random_1= tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1= random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(41)
random_2=random_2.normal(shape=(3,2))
print(random_2)
print(random_1)
random_1==random_2

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.31662667 -1.4391748 ]
 [ 0.58923835 -1.4268045 ]
 [-0.7565803  -0.06854702]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

# Shuffle the order of elements in tensor ( Aynı veri türlerini karıştırmak, öbür türlü hep aynı data türünü tararsa diğer türler ile karşılaştıramaz)

In [92]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

2

In [93]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [94]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

# Turn numpy arrays into Tensors

In [95]:
#The main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
#x=tf.constant(some_matrix) # capital for matrix or tensors
#y =tf.constant(vector) # non-capital for vector
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [96]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

 Getting information from tensors
 *Shape
 
 *Rank
 
 *Axis or dimension
 
 *Size
 
 
 # Create a rank 4 tensor (4 dimensions)
 

In [97]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [98]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [99]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [100]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [101]:
# Get Various attributes of our tensor
print("Datatype of every elemen:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor",tf.size(rank_4_tensor))
print("Total number of elements in our tensor",tf.size(rank_4_tensor).numpy())

Datatype of every elemen: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


# Indexing Tensors
Tensors can be indexed just like Python lists.

In [102]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [103]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [104]:
# Create a rank 2 tensor (2 dimensions)
rank_3_tensor=tf.constant([[[10,7,3],
                         [3,4,3]],
                           
                        [[1,2,3],
                           [1,2,1]]])
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([2, 2, 3]), 3)

In [105]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[10,  7,  3],
        [ 3,  4,  3]],

       [[ 1,  2,  3],
        [ 1,  2,  1]]])>

In [106]:
rank_3_tensor[:,0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 1,  2,  3]])>

In [107]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_3_tensor[...,tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 3, 1), dtype=int32, numpy=
array([[[[10],
         [ 7],
         [ 3]],

        [[ 3],
         [ 4],
         [ 3]]],


       [[[ 1],
         [ 2],
         [ 3]],

        [[ 1],
         [ 2],
         [ 1]]]])>

In [108]:
# Alternative to tf.newaxis
tf.expand_dims(rank_3_tensor,axis=-1) # -1 refers to expand the final axis
rank_3_tensor

<tf.Tensor: shape=(2, 2, 3, 1), dtype=int32, numpy=
array([[[[10],
         [ 7],
         [ 3]],

        [[ 3],
         [ 4],
         [ 3]]],


       [[[ 1],
         [ 2],
         [ 3]],

        [[ 1],
         [ 2],
         [ 1]]]])>

In [109]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis

NameError: name 'rank_2_tensor' is not defined

# Manipulating Tensors (Tensor Operations)
**Basic Operations**

In [110]:
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [111]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [112]:
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

# Multiplication

In [113]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [114]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [115]:
# We can use the tensorflow built-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [116]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

# Matrix Multiplication

In [117]:
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [118]:
tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]])>

In [119]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]])>

In [120]:
# Matrix Multiplication
tensor@tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]])>

# Reshaping

In [121]:
tf.reshape(tensor,shape=(1,4))


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[20, 17, 13, 14]])>

# Transpose

In [122]:
tf.transpose(tensor) ,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 13],
        [17, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>)

# The Dot Product
Matrix multiplication is also referred to as the dot product. 
We can perform matrix multiplication using;
tf.matmul()
tf.tensordot()


In [123]:
X=tf.constant([[1,2],
              [3,4],
              [5,6]])
Y=tf.constant([[7,8],
              [9,10],
              [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [124]:
#Perform Matrix Multiplication between X and Y(transpose)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [125]:
#Perform matrix multiplication between X and Y(reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [126]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesnt line up, we will transpose one of the tensors to get satisfy the matrix multiplication rules


# Create a new tensor with default datatype (float32)

In [127]:
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [128]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [129]:
# Change from float32 to float16 (reduced precision)
D=tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [130]:
# Change from int32 to float 32
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [131]:
E_float16= tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

# Aggregation Tensors
Aggregation tensors= condensing them from multiple values down to a smaller amount of values

In [132]:
D= tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [133]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [134]:
# More aggregation
E=tf.constant(np.random.randint(0,100,size=(50)))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([72, 31, 33, 84, 75, 67, 56, 99, 59, 43,  3, 55, 50, 44, 46, 89, 75,
       78, 19, 57, 98, 95, 21, 51, 36, 88, 68, 68, 24, 45, 49, 33, 88, 68,
       38, 82,  7, 19,  2, 80, 54, 94, 32, 52, 21, 23, 86, 80, 11, 74])>

In [135]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [136]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [137]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [138]:
# Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [139]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2722>

In [140]:
#  Variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.6; Detected an installation of version 2.3.0. Please upgrade TensorFlow to proceed.

In [142]:
# Find the variance of our E tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=731.0864>

# Find the positional maximum and minimum

In [143]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [145]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [146]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [147]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [149]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [150]:
# Find the position of Minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [151]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor (removing all single dimensions)

In [153]:
# Create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [154]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-hot Encoding Tensors

In [157]:
# Create a list of indices
some_list = [0,1,2,3]
tf.one_hot(some_list,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [159]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="umut",off_value="dundar")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'umut', b'dundar', b'dundar', b'dundar'],
       [b'dundar', b'umut', b'dundar', b'dundar'],
       [b'dundar', b'dundar', b'umut', b'dundar'],
       [b'dundar', b'dundar', b'dundar', b'umut']], dtype=object)>

# Squaring,log square root

In [161]:
H=tf.range(1,10)
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [165]:
# Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [168]:
# Find the log of the array
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [171]:
J = tf.constant(np.array([3.,5.,7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 7.])>

In [172]:
# Conver out tensor back to a NumPy array
np.array(J),type(np.array(J))

(array([3., 5., 7.]), numpy.ndarray)

In [173]:
# Conver tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([3., 5., 7.]), numpy.ndarray)

In [174]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [176]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype
# Tensors and numpy arrays has different kind of data type

(tf.float64, tf.float32)

# Finding access to GPUs

In [177]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]